version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - appnetwork
    depends_on:
      - db
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD_FILE: /run/secrets/db_password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    secrets:
      - db_password
    networks:
      - appnetwork
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - appnetwork
    depends_on:
      - webapp
    restart: always

secrets:
  db_password:
    file: ./secrets/db_password.txt

networks:
  appnetwork:
    driver: bridge
