version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"  # Change 443 to 8443 for external access
      - "8080:80"     # Keep port 80 for HTTP (optional)
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - appnetwork
    depends_on:
      - db
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD_FILE: /run/secrets/db_password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    secrets:
      - db_password
    networks:
      - appnetwork
    restart: always

secrets:
  db_password:
    file: ./secrets/db_password.txt

networks:
  appnetwork:
    driver: bridge
